const express = require('express');
const { register, login,recupera_clave ,getUsuarios ,deleteUsuario } = require('../controllers/authController');
const { authenticateToken } = require('../middleware/auth');
const { authorize } = require('../middleware/authorize');
const router = express.Router();
router.post('/register', register);
router.post('/login', login);
router.post('/recupera_clave', recupera_clave);
router.get('/getUsuarios', authenticateToken, authorize('ADMIN'), getUsuarios);
router.post('/deleteUsuario', authenticateToken, authorize('ADMIN'), deleteUsuario);
module.exports = router;
